# GNU make makefile for PMUniText (GCC / kLIBC)
#
# Tools: gcc, make, wrc (watcom-wrc).  Run from the project root (compile_gcc.cmd).
# Output goes to bin-gcc/ (the exe looks for lang/ next to itself).

SRC = src
BIN = bin-gcc
OS2TK ?= C:/os2tk45

CFLAGS = -Wall -O2 -Zomf -DOS2EMX_PLAIN_CHAR -I$(SRC)

HEADERS = $(SRC)/main.h $(SRC)/uni.h $(SRC)/lang.h
OBJS = $(BIN)/main.obj $(BIN)/uni.obj $(BIN)/lang.obj

all : $(BIN)/pmunitext.exe copylang

$(BIN)/%.obj : $(SRC)/%.c $(HEADERS)
	gcc $(CFLAGS) -c $< -o $@

$(BIN)/main.res : $(SRC)/main.rc $(SRC)/main.h
	wrc -r -q -bt=os2 -i=$(OS2TK)/h -i=$(SRC) -fo=$@ $(SRC)/main.rc

$(BIN)/pmunitext.exe : $(OBJS) $(BIN)/main.res $(SRC)/pmunitext.def
	gcc -Zomf $(OBJS) $(SRC)/pmunitext.def -o $@
	wrc -q -bt=os2 $(BIN)/main.res $@

copylang :
	-if not exist $(subst /,\,$(BIN)/lang) md $(subst /,\,$(BIN)/lang)
	copy $(subst /,\,lang/*.txt) $(subst /,\,$(BIN)/lang) > nul

clean :
	rm -f $(BIN)/*.obj $(BIN)/*.res $(BIN)/pmunitext.exe

.PHONY : all copylang clean
